# fly.toml: Fly v2 config for Homebridge with UI on 8080, HomeKit on 51826

app = "homebridge-fly"
primary_region = "fra"

[build]

[[mounts]]
  source = "homebridge"
  destination = "/homebridge"

[http_service]
  # Web UI beží vnútri kontajnera na porte 8080
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[tcp_services]]
  # HomeKit port 51826 (surové TCP pre HomeKit protokol)
  internal_port = 51826
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
